# Generated by Django 5.1.4 on 2025-01-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_staff_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='theme_color',
            field=models.CharField(default='blue', max_length=20, null=True),
        ),
    ]
