# Generated by Django 5.1.4 on 2025-01-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noter', '0002_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=20)),
                ('start_at', models.DateField(blank=True, null=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('list', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='noter.list')),
            ],
        ),
    ]
