# Generated by Django 5.1.4 on 2025-01-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noter', '0003_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='list',
            new_name='listinside',
        ),
    ]
