# Generated by Django 5.1.4 on 2025-01-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noter', '0004_rename_list_note_listinside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='listinside',
            new_name='list',
        ),
    ]
