# Generated by Django 5.1.4 on 2025-01-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noter', '0005_rename_listinside_note_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='color',
            field=models.CharField(default='gray', max_length=15),
        ),
    ]
