# Generated by Django 5.1.4 on 2025-01-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noter', '0006_alter_list_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='color',
            field=models.CharField(default='default', max_length=15),
        ),
    ]
