# Generated by Django 5.1.4 on 2025-01-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noter', '0007_alter_list_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
