name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: vernal-zone-455911-n4
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate with service account
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
        gcloud config set project vernal-zone-455911-n4

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet
