name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: vernal-zone-455911-n4               # ✅ Replace this with your actual Project ID
        export_default_credentials: true          # ✅ Required for gcloud CLI to use the credentials

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet
