
name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: vernal-zone-455911-n4               # ← Replace with your actual project ID
        service_account_key: ${{ secrets.GCP_SA_KEY }} # ← Must be a valid JSON string
        export_default_credentials: true               # ← REQUIRED to make gcloud commands work

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --quiet
